# automatically generated by the FlatBuffers compiler, do not modify

# namespace: SampleClient

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class List_of_Clients(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = List_of_Clients()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsList_of_Clients(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # List_of_Clients
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # List_of_Clients
    def Clients(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from SampleClient.Client import Client
            obj = Client()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # List_of_Clients
    def ClientsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # List_of_Clients
    def ClientsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def List_of_ClientsStart(builder): builder.StartObject(1)
def Start(builder):
    return List_of_ClientsStart(builder)
def List_of_ClientsAddClients(builder, clients): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(clients), 0)
def AddClients(builder, clients):
    return List_of_ClientsAddClients(builder, clients)
def List_of_ClientsStartClientsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def StartClientsVector(builder, numElems):
    return List_of_ClientsStartClientsVector(builder, numElems)
def List_of_ClientsEnd(builder): return builder.EndObject()
def End(builder):
    return List_of_ClientsEnd(builder)